-- +goose Up
-- Add team crest URLs. Values point at locally-served PNG assets under
-- frontend/public/logos/, populated by scripts/scrape_logos.py from
-- football-logos.cc. Nullable so unmapped teams (or future additions)
-- gracefully fall back to a monogram placeholder in the UI.
--
-- Source: football-logos.cc (no explicit license; attributed in README).
ALTER TABLE teams ADD COLUMN logo_url text;

UPDATE teams SET logo_url = '/logos/england--liverpool.png' WHERE name = 'Liverpool';
UPDATE teams SET logo_url = '/logos/england--arsenal.png' WHERE name = 'Arsenal';
UPDATE teams SET logo_url = '/logos/england--manchester-city.png' WHERE name = 'Manchester City';
UPDATE teams SET logo_url = '/logos/england--chelsea.png' WHERE name = 'Chelsea';
UPDATE teams SET logo_url = '/logos/england--newcastle.png' WHERE name = 'Newcastle United';
UPDATE teams SET logo_url = '/logos/england--aston-villa.png' WHERE name = 'Aston Villa';
UPDATE teams SET logo_url = '/logos/england--nottingham-forest.png' WHERE name = 'Nottingham Forest';
UPDATE teams SET logo_url = '/logos/england--brighton.png' WHERE name = 'Brighton & Hove Albion';
UPDATE teams SET logo_url = '/logos/england--bournemouth.png' WHERE name = 'AFC Bournemouth';
UPDATE teams SET logo_url = '/logos/england--brentford.png' WHERE name = 'Brentford';
UPDATE teams SET logo_url = '/logos/england--fulham.png' WHERE name = 'Fulham';
UPDATE teams SET logo_url = '/logos/england--crystal-palace.png' WHERE name = 'Crystal Palace';
UPDATE teams SET logo_url = '/logos/england--everton.png' WHERE name = 'Everton';
UPDATE teams SET logo_url = '/logos/england--west-ham.png' WHERE name = 'West Ham United';
UPDATE teams SET logo_url = '/logos/england--manchester-united.png' WHERE name = 'Manchester United';
UPDATE teams SET logo_url = '/logos/england--wolves.png' WHERE name = 'Wolverhampton Wanderers';
UPDATE teams SET logo_url = '/logos/england--tottenham.png' WHERE name = 'Tottenham Hotspur';
UPDATE teams SET logo_url = '/logos/england--leeds-united.png' WHERE name = 'Leeds United';
UPDATE teams SET logo_url = '/logos/england--burnley.png' WHERE name = 'Burnley';
UPDATE teams SET logo_url = '/logos/england--sunderland.png' WHERE name = 'Sunderland';
UPDATE teams SET logo_url = '/logos/spain--real-madrid.png' WHERE name = 'Real Madrid';
UPDATE teams SET logo_url = '/logos/spain--barcelona.png' WHERE name = 'FC Barcelona';
UPDATE teams SET logo_url = '/logos/spain--atletico-madrid.png' WHERE name = 'Atletico Madrid';
UPDATE teams SET logo_url = '/logos/spain--athletic-club.png' WHERE name = 'Athletic Club';
UPDATE teams SET logo_url = '/logos/spain--real-sociedad.png' WHERE name = 'Real Sociedad';
UPDATE teams SET logo_url = '/logos/spain--real-betis.png' WHERE name = 'Real Betis';
UPDATE teams SET logo_url = '/logos/spain--villarreal.png' WHERE name = 'Villarreal CF';
UPDATE teams SET logo_url = '/logos/spain--valencia.png' WHERE name = 'Valencia CF';
UPDATE teams SET logo_url = '/logos/spain--sevilla.png' WHERE name = 'Sevilla FC';
UPDATE teams SET logo_url = '/logos/spain--girona.png' WHERE name = 'Girona FC';
UPDATE teams SET logo_url = '/logos/spain--celta.png' WHERE name = 'Celta Vigo';
UPDATE teams SET logo_url = '/logos/spain--osasuna.png' WHERE name = 'CA Osasuna';
UPDATE teams SET logo_url = '/logos/spain--mallorca.png' WHERE name = 'RCD Mallorca';
UPDATE teams SET logo_url = '/logos/spain--rayo-vallecano.png' WHERE name = 'Rayo Vallecano';
UPDATE teams SET logo_url = '/logos/spain--getafe.png' WHERE name = 'Getafe CF';
UPDATE teams SET logo_url = '/logos/spain--espanyol.png' WHERE name = 'RCD Espanyol';
UPDATE teams SET logo_url = '/logos/spain--deportivo.png' WHERE name = 'Deportivo Alaves';
UPDATE teams SET logo_url = '/logos/spain--levante.png' WHERE name = 'Levante UD';
UPDATE teams SET logo_url = '/logos/spain--elche.png' WHERE name = 'Elche CF';
UPDATE teams SET logo_url = '/logos/spain--oviedo.png' WHERE name = 'Real Oviedo';
UPDATE teams SET logo_url = '/logos/germany--bayern-munchen.png' WHERE name = 'Bayern Munich';
UPDATE teams SET logo_url = '/logos/germany--bayer-leverkusen.png' WHERE name = 'Bayer Leverkusen';
UPDATE teams SET logo_url = '/logos/germany--borussia-dortmund.png' WHERE name = 'Borussia Dortmund';
UPDATE teams SET logo_url = '/logos/germany--rb-leipzig.png' WHERE name = 'RB Leipzig';
UPDATE teams SET logo_url = '/logos/germany--vfb-stuttgart.png' WHERE name = 'VfB Stuttgart';
UPDATE teams SET logo_url = '/logos/germany--eintracht-frankfurt.png' WHERE name = 'Eintracht Frankfurt';
UPDATE teams SET logo_url = '/logos/germany--borussia-monchengladbach.png' WHERE name = 'Borussia Monchengladbach';
UPDATE teams SET logo_url = '/logos/germany--wolfsburg.png' WHERE name = 'VfL Wolfsburg';
UPDATE teams SET logo_url = '/logos/germany--freiburg.png' WHERE name = 'SC Freiburg';
UPDATE teams SET logo_url = '/logos/germany--mainz-05.png' WHERE name = '1. FSV Mainz 05';
UPDATE teams SET logo_url = '/logos/germany--hoffenheim.png' WHERE name = 'TSG Hoffenheim';
UPDATE teams SET logo_url = '/logos/germany--werder-bremen.png' WHERE name = 'Werder Bremen';
UPDATE teams SET logo_url = '/logos/germany--augsburg.png' WHERE name = 'FC Augsburg';
UPDATE teams SET logo_url = '/logos/germany--st-pauli.png' WHERE name = 'FC St. Pauli';
UPDATE teams SET logo_url = '/logos/germany--fc-heidenheim.png' WHERE name = '1. FC Heidenheim';
UPDATE teams SET logo_url = '/logos/germany--koln.png' WHERE name = '1. FC Koln';
UPDATE teams SET logo_url = '/logos/germany--hamburger-sv.png' WHERE name = 'Hamburger SV';
UPDATE teams SET logo_url = '/logos/germany--union-berlin.png' WHERE name = '1. FC Union Berlin';
UPDATE teams SET logo_url = '/logos/italy--inter.png' WHERE name = 'Inter Milan';
UPDATE teams SET logo_url = '/logos/italy--milan.png' WHERE name = 'AC Milan';
UPDATE teams SET logo_url = '/logos/italy--juventus.png' WHERE name = 'Juventus';
UPDATE teams SET logo_url = '/logos/italy--napoli.png' WHERE name = 'Napoli';
UPDATE teams SET logo_url = '/logos/italy--roma.png' WHERE name = 'AS Roma';
UPDATE teams SET logo_url = '/logos/italy--lazio.png' WHERE name = 'SS Lazio';
UPDATE teams SET logo_url = '/logos/italy--atalanta.png' WHERE name = 'Atalanta';
UPDATE teams SET logo_url = '/logos/italy--bologna.png' WHERE name = 'Bologna';
UPDATE teams SET logo_url = '/logos/italy--fiorentina.png' WHERE name = 'Fiorentina';
UPDATE teams SET logo_url = '/logos/italy--torino.png' WHERE name = 'Torino';
UPDATE teams SET logo_url = '/logos/italy--udinese.png' WHERE name = 'Udinese';
UPDATE teams SET logo_url = '/logos/italy--genoa.png' WHERE name = 'Genoa';
UPDATE teams SET logo_url = '/logos/italy--cagliari.png' WHERE name = 'Cagliari';
UPDATE teams SET logo_url = '/logos/italy--verona.png' WHERE name = 'Hellas Verona';
UPDATE teams SET logo_url = '/logos/italy--como-1907.png' WHERE name = 'Como';
UPDATE teams SET logo_url = '/logos/italy--lecce.png' WHERE name = 'Lecce';
UPDATE teams SET logo_url = '/logos/italy--parma.png' WHERE name = 'Parma';
UPDATE teams SET logo_url = '/logos/italy--cremonese.png' WHERE name = 'Cremonese';
UPDATE teams SET logo_url = '/logos/italy--pisa.png' WHERE name = 'Pisa';
UPDATE teams SET logo_url = '/logos/italy--sassuolo.png' WHERE name = 'Sassuolo';
UPDATE teams SET logo_url = '/logos/france--paris-saint-germain.png' WHERE name = 'Paris Saint-Germain';
UPDATE teams SET logo_url = '/logos/france--marseille.png' WHERE name = 'Olympique de Marseille';
UPDATE teams SET logo_url = '/logos/france--as-monaco.png' WHERE name = 'AS Monaco';
UPDATE teams SET logo_url = '/logos/france--lille.png' WHERE name = 'LOSC Lille';
UPDATE teams SET logo_url = '/logos/france--nice.png' WHERE name = 'OGC Nice';
UPDATE teams SET logo_url = '/logos/france--lyon.png' WHERE name = 'Olympique Lyonnais';
UPDATE teams SET logo_url = '/logos/france--rc-lens.png' WHERE name = 'RC Lens';
UPDATE teams SET logo_url = '/logos/france--rc-strasbourg-alsace.png' WHERE name = 'RC Strasbourg';
UPDATE teams SET logo_url = '/logos/france--rennes.png' WHERE name = 'Stade Rennais';
UPDATE teams SET logo_url = '/logos/france--toulouse.png' WHERE name = 'Toulouse FC';
UPDATE teams SET logo_url = '/logos/france--nantes.png' WHERE name = 'FC Nantes';
UPDATE teams SET logo_url = '/logos/france--brest.png' WHERE name = 'Stade Brestois';
UPDATE teams SET logo_url = '/logos/france--auxerre.png' WHERE name = 'Auxerre';
UPDATE teams SET logo_url = '/logos/france--le-havre-ac.png' WHERE name = 'Le Havre AC';
UPDATE teams SET logo_url = '/logos/france--angers.png' WHERE name = 'Angers SCO';
UPDATE teams SET logo_url = '/logos/france--lorient.png' WHERE name = 'FC Lorient';
UPDATE teams SET logo_url = '/logos/france--fc-metz.png' WHERE name = 'FC Metz';
UPDATE teams SET logo_url = '/logos/france--paris-fc.png' WHERE name = 'Paris FC';
UPDATE teams SET logo_url = '/logos/national--france-national-team.png' WHERE name = 'France';
UPDATE teams SET logo_url = '/logos/national--england-national-team.png' WHERE name = 'England';
UPDATE teams SET logo_url = '/logos/national--spain-national-team.png' WHERE name = 'Spain';
UPDATE teams SET logo_url = '/logos/national--germany-national-team.png' WHERE name = 'Germany';
UPDATE teams SET logo_url = '/logos/national--italy-national-team.png' WHERE name = 'Italy';
UPDATE teams SET logo_url = '/logos/national--portuguese-football-federation.png' WHERE name = 'Portugal';
UPDATE teams SET logo_url = '/logos/national--dutch-national-team.png' WHERE name = 'Netherlands';
UPDATE teams SET logo_url = '/logos/national--belgium-national-team.png' WHERE name = 'Belgium';
UPDATE teams SET logo_url = '/logos/national--croatia-national-team.png' WHERE name = 'Croatia';
UPDATE teams SET logo_url = '/logos/national--switzerland-national-team.png' WHERE name = 'Switzerland';
UPDATE teams SET logo_url = '/logos/national--denmark-national-team.png' WHERE name = 'Denmark';
UPDATE teams SET logo_url = '/logos/national--austria-national-team.png' WHERE name = 'Austria';
UPDATE teams SET logo_url = '/logos/national--poland-national-team.png' WHERE name = 'Poland';
UPDATE teams SET logo_url = '/logos/national--sweden-national-team.png' WHERE name = 'Sweden';
UPDATE teams SET logo_url = '/logos/national--ukraine-national-team.png' WHERE name = 'Ukraine';
UPDATE teams SET logo_url = '/logos/national--turkey-national-team.png' WHERE name = 'Türkiye';
UPDATE teams SET logo_url = '/logos/national--serbia-national-team.png' WHERE name = 'Serbia';
UPDATE teams SET logo_url = '/logos/national--wales-national-team.png' WHERE name = 'Wales';
UPDATE teams SET logo_url = '/logos/national--hungary-national-team.png' WHERE name = 'Hungary';
UPDATE teams SET logo_url = '/logos/national--czech-republic-national-team.png' WHERE name = 'Czech Republic';
UPDATE teams SET logo_url = '/logos/national--norway-national-team.png' WHERE name = 'Norway';
UPDATE teams SET logo_url = '/logos/national--scotland-national-team.png' WHERE name = 'Scotland';
UPDATE teams SET logo_url = '/logos/national--brazil-national-team.png' WHERE name = 'Brazil';
UPDATE teams SET logo_url = '/logos/national--argentina-national-team.png' WHERE name = 'Argentina';
UPDATE teams SET logo_url = '/logos/national--uruguay-national-team.png' WHERE name = 'Uruguay';
UPDATE teams SET logo_url = '/logos/national--colombia-national-team.png' WHERE name = 'Colombia';
UPDATE teams SET logo_url = '/logos/national--ecuador-national-team.png' WHERE name = 'Ecuador';
UPDATE teams SET logo_url = '/logos/national--peru-national-team.png' WHERE name = 'Peru';
UPDATE teams SET logo_url = '/logos/national--chile-national-team.png' WHERE name = 'Chile';
UPDATE teams SET logo_url = '/logos/national--paraguay-national-team.png' WHERE name = 'Paraguay';
UPDATE teams SET logo_url = '/logos/national--venezuela-national-team.png' WHERE name = 'Venezuela';
UPDATE teams SET logo_url = '/logos/national--usa-national-team.png' WHERE name = 'USA';
UPDATE teams SET logo_url = '/logos/national--mexico-national-team.png' WHERE name = 'Mexico';
UPDATE teams SET logo_url = '/logos/national--canada-national-team.png' WHERE name = 'Canada';
UPDATE teams SET logo_url = '/logos/national--costa-rica-national-team.png' WHERE name = 'Costa Rica';
UPDATE teams SET logo_url = '/logos/national--panama-national-team.png' WHERE name = 'Panama';
UPDATE teams SET logo_url = '/logos/national--jamaica-national-team.png' WHERE name = 'Jamaica';
UPDATE teams SET logo_url = '/logos/national--japan-national-team.png' WHERE name = 'Japan';
UPDATE teams SET logo_url = '/logos/national--south-korea-national-team.png' WHERE name = 'South Korea';
UPDATE teams SET logo_url = '/logos/national--iran-national-team.png' WHERE name = 'Iran';
UPDATE teams SET logo_url = '/logos/national--australia-national-team.png' WHERE name = 'Australia';
UPDATE teams SET logo_url = '/logos/national--saudi-arabia-national-team.png' WHERE name = 'Saudi Arabia';
UPDATE teams SET logo_url = '/logos/national--qatar-national-team.png' WHERE name = 'Qatar';
UPDATE teams SET logo_url = '/logos/national--iraq-national-team.png' WHERE name = 'Iraq';
UPDATE teams SET logo_url = '/logos/national--morocco-national-team.png' WHERE name = 'Morocco';
UPDATE teams SET logo_url = '/logos/national--senegal-national-team.png' WHERE name = 'Senegal';
UPDATE teams SET logo_url = '/logos/national--egypt-national-team.png' WHERE name = 'Egypt';
UPDATE teams SET logo_url = '/logos/national--algeria-national-team.png' WHERE name = 'Algeria';
UPDATE teams SET logo_url = '/logos/national--nigeria-national-team.png' WHERE name = 'Nigeria';
UPDATE teams SET logo_url = '/logos/national--tunisia-national-team.png' WHERE name = 'Tunisia';
UPDATE teams SET logo_url = '/logos/national--cote-d-ivoire-national-team.png' WHERE name = 'Ivory Coast';
UPDATE teams SET logo_url = '/logos/national--cameroon-national-team.png' WHERE name = 'Cameroon';
UPDATE teams SET logo_url = '/logos/national--ghana-national-team.png' WHERE name = 'Ghana';

-- +goose Down
ALTER TABLE teams DROP COLUMN logo_url;
