-- Idempotent team catalog seed.
INSERT INTO teams (name, league, country, kind) VALUES
  -- Premier League
  ('Manchester City',     'Premier League', 'England', 'club'),
  ('Arsenal',             'Premier League', 'England', 'club'),
  ('Liverpool',           'Premier League', 'England', 'club'),
  ('Manchester United',   'Premier League', 'England', 'club'),
  ('Chelsea',             'Premier League', 'England', 'club'),
  ('Tottenham Hotspur',   'Premier League', 'England', 'club'),
  ('Newcastle United',    'Premier League', 'England', 'club'),
  ('Aston Villa',         'Premier League', 'England', 'club'),
  ('West Ham United',     'Premier League', 'England', 'club'),
  ('Brighton & Hove Albion', 'Premier League', 'England', 'club'),
  -- La Liga
  ('Real Madrid',         'La Liga', 'Spain', 'club'),
  ('FC Barcelona',        'La Liga', 'Spain', 'club'),
  ('Atletico Madrid',     'La Liga', 'Spain', 'club'),
  ('Sevilla FC',          'La Liga', 'Spain', 'club'),
  ('Real Sociedad',       'La Liga', 'Spain', 'club'),
  ('Real Betis',          'La Liga', 'Spain', 'club'),
  ('Athletic Club',       'La Liga', 'Spain', 'club'),
  ('Villarreal CF',       'La Liga', 'Spain', 'club'),
  ('Valencia CF',         'La Liga', 'Spain', 'club'),
  ('Girona FC',           'La Liga', 'Spain', 'club'),
  -- Bundesliga
  ('Bayern Munich',       'Bundesliga', 'Germany', 'club'),
  ('Borussia Dortmund',   'Bundesliga', 'Germany', 'club'),
  ('RB Leipzig',          'Bundesliga', 'Germany', 'club'),
  ('Bayer Leverkusen',    'Bundesliga', 'Germany', 'club'),
  ('Eintracht Frankfurt', 'Bundesliga', 'Germany', 'club'),
  ('VfB Stuttgart',       'Bundesliga', 'Germany', 'club'),
  ('VfL Wolfsburg',       'Bundesliga', 'Germany', 'club'),
  ('Borussia Monchengladbach', 'Bundesliga', 'Germany', 'club'),
  ('SC Freiburg',         'Bundesliga', 'Germany', 'club'),
  ('1. FC Union Berlin',  'Bundesliga', 'Germany', 'club'),
  -- Serie A
  ('Inter Milan',         'Serie A', 'Italy', 'club'),
  ('AC Milan',            'Serie A', 'Italy', 'club'),
  ('Juventus',            'Serie A', 'Italy', 'club'),
  ('AS Roma',             'Serie A', 'Italy', 'club'),
  ('SSC Napoli',          'Serie A', 'Italy', 'club'),
  ('SS Lazio',            'Serie A', 'Italy', 'club'),
  ('Atalanta BC',         'Serie A', 'Italy', 'club'),
  ('ACF Fiorentina',      'Serie A', 'Italy', 'club'),
  ('Bologna FC',          'Serie A', 'Italy', 'club'),
  ('Torino FC',           'Serie A', 'Italy', 'club'),
  -- Ligue 1
  ('Paris Saint-Germain', 'Ligue 1', 'France', 'club'),
  ('Olympique de Marseille', 'Ligue 1', 'France', 'club'),
  ('Olympique Lyonnais',  'Ligue 1', 'France', 'club'),
  ('AS Monaco',           'Ligue 1', 'France', 'club'),
  ('LOSC Lille',          'Ligue 1', 'France', 'club'),
  ('OGC Nice',            'Ligue 1', 'France', 'club'),
  ('Stade Rennais',       'Ligue 1', 'France', 'club'),
  ('RC Lens',             'Ligue 1', 'France', 'club'),
  ('FC Nantes',           'Ligue 1', 'France', 'club'),
  ('Stade Brestois',      'Ligue 1', 'France', 'club'),
  -- Neutral fictional
  ('Red Lions FC',        'Neutral', 'Fictional', 'neutral'),
  ('Northern United',     'Neutral', 'Fictional', 'neutral'),
  ('Coastal Rangers',     'Neutral', 'Fictional', 'neutral'),
  ('Capital Athletic',    'Neutral', 'Fictional', 'neutral'),
  ('Mountain City',       'Neutral', 'Fictional', 'neutral')
ON CONFLICT (name) DO NOTHING;
